<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Bcandidate extends Model{
    public function gvote(){
         return $this->hasMany('App\Models\gvote');
}
}