<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Celector extends Model{
    public function gvote(){ return $this->hasOne('App\Models\gvote'); }
}