<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Dpavilion extends Model{
    public function eclassroom(){ return $this->hasMany('App\Models\eclassroom'); }
}