<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Eclassroom extends Model{
public function fcabin(){ return $this->hasOne('App\Models\Fcabin'); }
public function dpavilion(){ return $this->belongsTo('App\Models\dpavilion'); }
}