<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Gvote extends Model{
public function celector(){ return $this->belongsTo('App\Models\Celector'); }
}